// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.501
package user

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "go-htmx-fiber/views/layouts"

func SignUpForm() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form action=\"POST\" class=\"w-1/2 mx-auto\"><div><div class=\"\n									h-20\n									mb-4\n									grid grid-cols-12\n									text-lg\n									items-center\n									justify-center\n								\"><label for=\"email\" class=\"mr-4 col-span-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var3 := `Email`
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</label> <input type=\"text\" id=\"email\" name=\"email\" class=\"\n										col-start-4 col-span-9\n										items-center\n										text-left text-lg\n										space-x-3\n										px-4\n										h-12\n										bg-white\n										ring-1 ring-slate-900/10\n										hover:ring-slate-300\n										focus:outline-none focus:ring-2 focus:ring-sky-500\n										shadow-sm\n										rounded-lg\n										text-slate-400\n										dark:bg-slate-800\n										dark:ring-0\n										dark:text-slate-300\n										dark:highlight-white/5\n										dark:hover:bg-slate-700\n									\"></div><div class=\"\n									h-20\n									mb-4\n									grid grid-cols-12\n									text-lg\n									items-center\n									justify-center\n								\"><label for=\"password\" class=\"mr-4 col-span-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var4 := `Password`
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</label> <input type=\"password\" id=\"password\" name=\"password\" class=\"\n										col-start-4 col-span-9\n										items-center\n										text-left text-lg\n										space-x-3\n										px-4\n										h-12\n										bg-white\n										ring-1 ring-slate-900/10\n										hover:ring-slate-300\n										focus:outline-none focus:ring-2 focus:ring-sky-500\n										shadow-sm\n										rounded-lg\n										text-slate-400\n										dark:bg-slate-800\n										dark:ring-0\n										dark:text-slate-300\n										dark:highlight-white/5\n										dark:hover:bg-slate-700\n									\"></div><div class=\"w-full\"><button hx-post=\"/sign-up\" hx-target=\"#test-div\" hx-swap=\"innerHTML\" class=\"\n										mx-auto\n										bg-slate-900\n										hover:bg-slate-700\n										focus:outline-none\n										focus:ring-2\n										focus:ring-slate-400\n										focus:ring-offset-2\n										focus:ring-offset-slate-50\n										text-white\n										font-semibold\n										h-12\n										px-6\n										rounded-lg\n										w-full\n										flex\n										items-center\n										justify-center\n										sm:w-auto\n										dark:bg-sky-500 dark:highlight-white/20 dark:hover:bg-sky-400\n									\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var5 := `Log In`
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button></div></div></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
